### ISSUE TITLE
update your Readme for gem usage - replace require 'openai' with require 'ruby/openai'

### ISSUE THREAD

**Issue by jeffrono** [alexrudall/ruby-openai#271]
I followed the instructions for a basic test in ruby and after a lot of issues and errors in terminal, realized the issue was that I was using
`require "openai"` (from the readme)
but it should be
`require 'ruby/openai'`

This is on mac ventura 13.4. 

please update the readme 🙏

**Comment by ScotterC** [comment]
hey @jeffrono 👋 . What version are you using? I believe that the change in require statements happened in 4.0 but <4.0 it was `require 'ruby/openai'`

**Comment by jeffrono** [comment]
Hey. I’m using the latest version I think 4.1.0.  However I’m on ruby 2.6.0 I think if that makes any difference? --------Jeff ***@***.*** Jun 1, 2023, at 8:25 PM, Scott Carleton ***@***.***> wrote:﻿
hey @jeffrono 👋 . What version are you using? I believe that the change in require statements happened in 4.0 but <4.0 it was require 'ruby/openai'

**Comment by b08x** [comment]
The issue seems to be having both the `openai(0.3.0)` and `ruby-openai(4.1.0)` gems installed

I ran into the same issue today using a 3.2.0 gemset where `openai (0.3.0) ` was also installed as it appears the gems have a conflicting namespace. 

```ruby
1: require 'openai'
2: OpenAI.configure do |config|
     config.access_token = ENV['OPENAI_ACCESS_TOKEN']
   end

   NoMethodError: undefined method `configure' for OpenAI:Module
```

Removing the `openai (0.3.0) ` gem resolves this particular undefined method error.
