### ISSUE TITLE
Error: initialize': missing keyword: :api_key

### ISSUE THREAD

**Issue by DogAndCode** [alexrudall/ruby-openai#293]
I'm having this error everytime I try to acces to the API:

I have tryied with this: 
```client = OpenAI::Client.new(access_token: Rails.application.credentials.dig(:openai, :api_key))```

and this:
```client = OpenAI::Client.new(access_token: "my_access_token")```

And none of them have worked.

I have on my credentials file the api key correctly saved

**Comment by bartjacobs** [comment]
@DogAndCode I believe this is the result of a naming collision. Do you have the [openai](https://rubygems.org/gems/openai) gem installed? That gem defines an initializer that accepts an API key instead of an access token (although they are the same thing). The solution is to uninstall the **openai** gem to resolve the naming collision. You can also use a Gemfile if uninstalling the **openai** gem isn't an option.

**Comment by DogAndCode** [comment]
@bartjacobs thanks for your answer man. You were totally right. Just deleted openai gem and it works as good as always.

Thanks again

**Comment by DogAndCode** [comment]
This is solved

**Comment by kaibadash** [comment]
📝 I have solved it with the following commands
```
gem uninstall openai
 ```
